			insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (1 , 'Adana', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (2 , 'Adıyaman', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (3 , 'Afyon', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (4 , 'Ağrı', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (5 , 'Amasya', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (6 , 'Ankara', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (7 , 'Antalya', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (8 , 'Artvin', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (9 , 'Aydın', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (10, 'Balıkesir', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (11, 'Bilecik', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (12, 'Bingöl', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (13, 'Bitlis', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (14, 'Bolu', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (15, 'Burdur', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (16, 'Bursa', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (17, 'Çanakkale', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (18, 'Çankırı', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (19, 'Çorum', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (20, 'Denizli', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (21, 'Diyarbakır', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (22, 'Edirne', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (23, 'Elazığ', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (24, 'Erzincan', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (25, 'Erzurum', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (26, 'Eskişehir', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (27, 'Gaziantep', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (28, 'Giresun', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (29, 'Gümüşhane', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (30, 'Hakkari', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (31, 'Hatay', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (32, 'Isparta', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (33, 'Mersin', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (34, 'İstanbul', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (35, 'İzmir', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (36, 'Kars', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (37, 'Kastamonu', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (38, 'Kayseri', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (39, 'Kırklareli', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (40, 'Kırşehir', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (41, 'Kocaeli', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (42, 'Konya', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (43, 'Kütahya', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (44, 'Malatya', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (45, 'Manisa', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (46, 'Kahramanmaraş', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (47, 'Mardin', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (48, 'Muğla', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (49, 'Muş', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (50, 'Nevşehir', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (51, 'Niğde', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (52, 'Ordu', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (53, 'Rize', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (54, 'Sakarya', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (55, 'Samsun', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (56, 'Siirt', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (57, 'Sinop', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (58, 'Sivas', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (59, 'Tekirdağ', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (60, 'Tokat', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (61, 'Trabzon', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (62, 'Tunceli', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (63, 'Şanlıurfa', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (64, 'Uşak', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (65, 'Van', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (66, 'Yozgat', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (67, 'Zonguldak', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (68, 'Aksaray', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (69, 'Bayburt', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (70, 'Karaman', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (71, 'Kırıkkale', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (72, 'Batman', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (73, 'Şırnak', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (74, 'Bartın', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (75, 'Ardahan', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (76, 'Iğdır', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (77, 'Yalova', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (78, 'Karabük', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (79, 'Kilis', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (80, 'Osmaniye', GETDATE(),0)
            insert into Cities (PlateCode,CityName,CreatedDate,IsDeleted)  values (81, 'Düzce', GETDATE(),0)